title: Aman Vijaywargi
description: I am a frontend developer who works for RD&X Network. I have a 1 year experience for frontend development in React, Redux. I have even worked in backbonejs also
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
